### ISSUE TITLE
ACR servers not working?

### ISSUE THREAD

**Issue by xDwightPlays** [acreloaded/acr#193]
Guys i dunno but the masterserver aint replying i already tried to let ACR through the firewall but still nothings happening
Please Help been in ACR for half a month now and still not working :P

**Comment by theonlypwner** [comment]
The master-server sometimes has issues, but it seems to be working right now. I saw one server on it.

Unfortunately, there are almost no servers and players because ACR started with few servers and players and failed to grow. Even worse is that ACR has been inactive recently, but a new release will be made around the start of January. This is almost a year after the previous release, in contrast to the frequent releases in the past.

**Comment by xDwightPlays** [comment]
the masterserver is not replying I apologize but I think I made a mistake
will you please bother to help me out.

**Comment by xDwightPlays** [comment]
ok ok tnx got it
