### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by d-damien** [acreloaded/acr#204]
Hi,

According to git log, ACR has been existing for at least three years and a half... and I just heard about it, although I have been knowing AC for a long time now.

- seaching
> "assaultcube reloaded" OR acr site:assault.cubers.net

gives no result

- nothing on wikipedia pages

- nothing on Getdeb (ok this one necessitates a bit of work)

Of course, I understand you cannot take care of everything, but you should ask your players to communicate a bit around it. I'm going to add it to Wikipedia and games directories.

Thank you for this (unknown) piece of work.

**Comment by theonlypwner** [comment]
ACR was actually created in December 2010, which is almost 7 years ago.

Wikipedia previously deleted our page because we aren't notable enough ([DRV](https://en.wikipedia.org/wiki/Wikipedia:Deletion_review/Log/2013_January_14), [AfD](https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/AssaultCube_Reloaded)).

The lack of players makes it hard for ACR to grow, and maintains that lack of players.
