### ISSUE TITLE
gamma name collision (can't compile on Arch Linux)

### ISSUE THREAD

**Issue by Valou3433** [acreloaded/acr#207]
I could not compile the game on arch linux, either by downloading and compiling manually or using AUR.
I looked at the errors and fixed them this way : 
in platform.h i commented out the redefinition of gamma, because it made the loading of math.h not possible 

```
#ifdef __GNUC__
    #ifdef _FORTIFY_SOURCE
        #undef _FORTIFY_SOURCE
    #endif

    //#define gamma __gamma
#endif

#include <math.h>

//#ifdef __GNUC__
//    #undef gamma
//#endif
```

and in main.cpp, i replaced the VARFP(gamma) at line 520 by
```
VARFP(rgamma, 30, 100, 300,
{
    if(rgamma == curgamma) return;
    curgamma = rgamma;
    float f = rgamma/100.0f;
    if(SDL_SetGamma(f,f,f)==-1) conoutf("Could not set gamma: %s", SDL_GetError());
});
```
because gamma was already defined before, in the math.h file i believe.

Then i could compile and run the game, and now it is working fine.
Just wanted to share that to let you know and to understand why were things done like that, if that was a compatibility issue or ?? (im using latest version of gcc, 7.2.1)

**Comment by Translator5** [comment]
same here

**Comment by theonlypwner** [comment]
ACR is based on AC 1.2.0.2 (previously based on 1.0.4), so we inherited their issues.

They've fixed this specific issue on 2016-02-26 in assaultcube/AC@98d01d1f34f49a49dae59478550e54d4aaf8cc91, but they haven't released a newer version since 2015.

---

For this issue, it'll eventually be fixed when we merge with their next release, or I can backport their fix (and risk having more merge issues later).

**Comment by r58iiz** [comment]
so does that mean it cant be compiled on linux?

**Comment by theonlypwner** [comment]
It can be compiled on Linux after resolving the name collision, but it would be easier if I just fix it, so I have decided to fix this.
